function [MB,MC,KB,KBP,GB,FB] = Finite_of_Beam2(Lb,Do,Di,P,sn)  %%用的是自己推导的形函数，与文献有所差别
format rat
%% Timshenko beam Finite element model including the stiffness of disk；both are circular section
global qx qy qz my mz pho E mju
% global MT MR Mc Kb Kbp
% pho=7.806e3;       % density of the rotor and bearings
% E=2.08e11;         % Young's Modulus of elasticity of the rotor and bearings
% mju=0.30;          % poission ratio
G=E/2/(1+mju);     % Shear Moulus of elasticity of the rotor and bearings
% to abtain MB、MC、KB、KBP、GB、FB
n = length(Lb);
Nof = 5*(n+1);
MB=zeros(Nof,Nof);
MC=zeros(Nof,Nof);
KB=zeros(Nof,Nof);
KBP=zeros(Nof,Nof);
GB=zeros(Nof,Nof);
FB=zeros(Nof,1);
for i=1:n
    A=pi*(Do(i)^2-Di(i)^2)/4;
    I=1/4*pi*((Do(i)/2)^4+(Di(i)/2)^4); 
    J=1/2*pi*((Do(i)/2)^4+(Di(i)/2)^4);
    L = Lb(i); 
    p = Di(i)/Do(i);
    ks = 6*(1+mju)*(1+p^2)^2/((7+6*mju)*(1+p^2)^2+(20+12*mju)*p^2);
 
MT =[ (A*L*pho)/3,                                                                                                    0,                                                                                                       0,                                                                                                         0,                                                                                                       0, (A*L*pho)/6,                                                                                                       0,                                                                                                         0,                                                                                                       0,                                                                                                         0
           0,       (13*A*L*pho)/35 - ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2,                                                                                                       0,                                                                                                         0, (11*A*L^2*pho)/210 - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2,           0,      ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (9*A*L*pho)/70,                                                                                                         0,                                                                                                       0, - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (13*A*L^2*pho)/420
           0,                                                                                                         0,     (13*A*L*pho)/35 - ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2,   ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (11*A*L^2*pho)/210,                                                                                                       0,           0,                                                                                                       0,        ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (9*A*L*pho)/70, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (13*A*L^2*pho)/420,                                                                                                         0
           0,                                                                                                         0, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (11*A*L^2*pho)/210,                                    (A*L^3*pho)/120 + (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2),                                                                                                       0,           0,                                                                                                       0, - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (13*A*L^2*pho)/420,                                  (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2) - (A*L^3*pho)/120,                                                                                                         0
           0,   (11*A*L^2*pho)/210 - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2,                                                                                                       0,                                                                                                         0,                                  (A*L^3*pho)/120 + (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2),           0, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (13*A*L^2*pho)/420,                                                                                                         0,                                                                                                       0,                                    (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2) - (A*L^3*pho)/120
 (A*L*pho)/6,                                                                                                         0,                                                                                                       0,                                                                                                         0,                                                                                                       0, (A*L*pho)/3,                                                                                                       0,                                                                                                         0,                                                                                                       0,                                                                                                         0
           0,        ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (9*A*L*pho)/70,                                                                                                       0,                                                                                                         0, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (13*A*L^2*pho)/420,           0,     (13*A*L*pho)/35 - ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2,                                                                                                         0,                                                                                                       0,   ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (11*A*L^2*pho)/210
           0,                                                                                                         0,      ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (9*A*L*pho)/70, - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (13*A*L^2*pho)/420,                                                                                                       0,           0,                                                                                                       0,       (13*A*L*pho)/35 - ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2, (11*A*L^2*pho)/210 - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2,                                                                                                         0
           0,                                                                                                         0, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (13*A*L^2*pho)/420,                                    (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2) - (A*L^3*pho)/120,                                                                                                       0,           0,                                                                                                       0,   (11*A*L^2*pho)/210 - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2,                                  (A*L^3*pho)/120 + (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2),                                                                                                         0
           0, - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (13*A*L^2*pho)/420,                                                                                                       0,                                                                                                         0,                                  (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2) - (A*L^3*pho)/120,           0, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (11*A*L^2*pho)/210,                                                                                                         0,                                                                                                       0,                                    (A*L^3*pho)/120 + (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2)];
MR =[0,                                                                      0,                                                                     0,                                                                                             0,                                                                                             0, 0,                                                                     0,                                                                      0,                                                                                             0,                                                                                             0
     0,                 (6*A^2*G^2*I*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                                     0,                                                                                             0,                        -(A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2), 0,               -(6*A^2*G^2*I*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                                      0,                                                                                             0,                        -(A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2)
     0,                                                                      0,                (6*A^2*G^2*I*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                         (A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                                             0, 0,                                                                     0,                -(6*A^2*G^2*I*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                         (A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                                             0
     0,                                                                      0, (A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2), ((144*E^2*I^3*L*pho)/5 - (6*A*E*G*I^2*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 + (2*I*L*pho)/15,                                                                                             0, 0,                                                                     0, -(A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),   ((144*E^2*I^3*L*pho)/5 - (6*A*E*G*I^2*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 - (I*L*pho)/30,                                                                                             0
     0, -(A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                     0,                                                                                             0, ((144*E^2*I^3*L*pho)/5 - (6*A*E*G*I^2*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 + (2*I*L*pho)/15, 0, (A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                      0,                                                                                             0,   ((144*E^2*I^3*L*pho)/5 - (6*A*E*G*I^2*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 - (I*L*pho)/30
     0,                                                                      0,                                                                     0,                                                                                             0,                                                                                             0, 0,                                                                     0,                                                                      0,                                                                                             0,                                                                                             0
     0,                -(6*A^2*G^2*I*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                                     0,                                                                                             0,                         (A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2), 0,                (6*A^2*G^2*I*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                                      0,                                                                                             0,                         (A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2)
     0,                                                                      0,               -(6*A^2*G^2*I*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                        -(A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                                             0, 0,                                                                     0,                 (6*A^2*G^2*I*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                        -(A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                                             0
     0,                                                                      0, (A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),   ((144*E^2*I^3*L*pho)/5 - (6*A*E*G*I^2*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 - (I*L*pho)/30,                                                                                             0, 0,                                                                     0, -(A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2), ((144*E^2*I^3*L*pho)/5 - (6*A*E*G*I^2*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 + (2*I*L*pho)/15,                                                                                             0
     0, -(A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                     0,                                                                                             0,   ((144*E^2*I^3*L*pho)/5 - (6*A*E*G*I^2*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 - (I*L*pho)/30, 0, (A*G*I*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                      0,                                                                                             0, ((144*E^2*I^3*L*pho)/5 - (6*A*E*G*I^2*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 + (2*I*L*pho)/15];
Mc =[0,                                                                                                         0,                                                                                                       0,                                                                                                         0,                                                                                                       0, 0,                                                                                                       0,                                                                                                         0,                                                                                                       0,                                                                                                         0
     0,       (13*A*L*pho)/35 - ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2,                                                                                                       0,                                                                                                         0, (11*A*L^2*pho)/210 - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2, 0,      ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (9*A*L*pho)/70,                                                                                                         0,                                                                                                       0, - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (13*A*L^2*pho)/420
     0,                                                                                                         0,     (13*A*L*pho)/35 - ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2,   ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (11*A*L^2*pho)/210,                                                                                                       0, 0,                                                                                                       0,        ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (9*A*L*pho)/70, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (13*A*L^2*pho)/420,                                                                                                         0
     0,                                                                                                         0, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (11*A*L^2*pho)/210,                                    (A*L^3*pho)/120 + (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2),                                                                                                       0, 0,                                                                                                       0, - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (13*A*L^2*pho)/420,                                  (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2) - (A*L^3*pho)/120,                                                                                                         0
     0,   (11*A*L^2*pho)/210 - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2,                                                                                                       0,                                                                                                         0,                                  (A*L^3*pho)/120 + (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2), 0, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (13*A*L^2*pho)/420,                                                                                                         0,                                                                                                       0,                                    (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2) - (A*L^3*pho)/120
     0,                                                                                                         0,                                                                                                       0,                                                                                                         0,                                                                                                       0, 0,                                                                                                       0,                                                                                                         0,                                                                                                       0,                                                                                                         0
     0,        ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (9*A*L*pho)/70,                                                                                                       0,                                                                                                         0, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (13*A*L^2*pho)/420, 0,     (13*A*L*pho)/35 - ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2,                                                                                                         0,                                                                                                       0,   ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (11*A*L^2*pho)/210
     0,                                                                                                         0,      ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (9*A*L*pho)/70, - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (13*A*L^2*pho)/420,                                                                                                       0, 0,                                                                                                       0,       (13*A*L*pho)/35 - ((18*G*ks*pho*A^2*E*I*L^3)/35 + (192*pho*A*E^2*I^2*L)/35)/(A*G*ks*L^2 + 12*E*I)^2, (11*A*L^2*pho)/210 - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2,                                                                                                         0
     0,                                                                                                         0, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 + (13*A*L^2*pho)/420,                                    (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2) - (A*L^3*pho)/120,                                                                                                       0, 0,                                                                                                       0,   (11*A*L^2*pho)/210 - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2,                                  (A*L^3*pho)/120 + (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2),                                                                                                         0
     0, - ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (13*A*L^2*pho)/420,                                                                                                       0,                                                                                                         0,                                  (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2) - (A*L^3*pho)/120, 0, ((11*G*ks*pho*A^2*E*I*L^4)/70 + (54*pho*A*E^2*I^2*L^2)/35)/(A*G*ks*L^2 + 12*E*I)^2 - (11*A*L^2*pho)/210,                                                                                                         0,                                                                                                       0,                                    (A*L^3*pho)/120 + (A^3*G^2*L^7*ks^2*pho)/(840*(A*G*ks*L^2 + 12*E*I)^2)];

Mb=MT+MR;
Gb =[0,                                                                     0,                                                                     0,                                                                                               0,                                                                                                 0, 0,                                                                      0,                                                                      0,                                                                                               0,                                                                                                 0
     0,                                                                     0,               -(6*A^2*G^2*J*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                          -(A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                                                 0, 0,                                                                      0,                 (6*A^2*G^2*J*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                          -(A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                                                 0
     0,                (6*A^2*G^2*J*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                                     0,                                                                                               0,                            -(A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2), 0,                -(6*A^2*G^2*J*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                                      0,                                                                                               0,                            -(A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2)
     0, (A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                     0,                                                                                               0, - ((144*E^2*I^2*J*L*pho)/5 - (6*A*E*G*I*J*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 - (2*J*L*pho)/15, 0, -(A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                      0,                                                                                               0,     (J*L*pho)/30 - ((144*E^2*I^2*J*L*pho)/5 - (6*A*E*G*I*J*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2
     0,                                                                     0, (A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2), ((144*E^2*I^2*J*L*pho)/5 - (6*A*E*G*I*J*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 + (2*J*L*pho)/15,                                                                                                 0, 0,                                                                      0, -(A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),   ((144*E^2*I^2*J*L*pho)/5 - (6*A*E*G*I*J*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 - (J*L*pho)/30,                                                                                                 0
     0,                                                                     0,                                                                     0,                                                                                               0,                                                                                                 0, 0,                                                                      0,                                                                      0,                                                                                               0,                                                                                                 0
     0,                                                                     0,                (6*A^2*G^2*J*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                           (A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                                                 0, 0,                                                                      0,                -(6*A^2*G^2*J*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                           (A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                                                 0
     0,               -(6*A^2*G^2*J*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                                     0,                                                                                               0,                             (A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2), 0,                 (6*A^2*G^2*J*L^3*ks^2*pho)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                                      0,                                                                                               0,                             (A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2)
     0, (A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                     0,                                                                                               0,     (J*L*pho)/30 - ((144*E^2*I^2*J*L*pho)/5 - (6*A*E*G*I*J*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2, 0, -(A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                                      0,                                                                                               0, - ((144*E^2*I^2*J*L*pho)/5 - (6*A*E*G*I*J*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 - (2*J*L*pho)/15
     0,                                                                     0, (A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2),   ((144*E^2*I^2*J*L*pho)/5 - (6*A*E*G*I*J*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 - (J*L*pho)/30,                                                                                                 0, 0,                                                                      0, -(A*G*J*L^2*ks*pho*(60*E*I - A*G*L^2*ks))/(10*(A*G*ks*L^2 + 12*E*I)^2), ((144*E^2*I^2*J*L*pho)/5 - (6*A*E*G*I*J*L^3*ks*pho)/5)/(A*G*ks*L^2 + 12*E*I)^2 + (2*J*L*pho)/15,                                                                                                 0];
    
%% 与结点位移有关的量
    ui = sn (5*i-4);        vi = sn(5*i-3);        wi = sn(5*i-2);         thyi = sn(5*i-1);         thzi = sn(5*i);
    uj = sn (5*(i+1)-4);    vj = sn(5*(i+1)-3);    wj = sn(5*(i+1)-2);     thyj = sn(5*(i+1)-1);     thzj = sn(5*(i+1));

FbC =[                                                                                                                                                                                                                                                                                                                                                                                                    (A*E*(ui - uj))/L
                                                                                                                                                                                                  A*G*ks*(thzi - (12*E*I*vj - 12*E*I*vi + 6*E*I*L*thzi - 6*E*I*L*thzj + A*G*L^3*ks*thzi)/(L*(A*G*ks*L^2 + 12*E*I))) - (P*(12*E*I*vj - 12*E*I*vi + 6*E*I*L*thzi - 6*E*I*L*thzj + A*G*L^3*ks*thzi))/(L*(A*G*ks*L^2 + 12*E*I))
                                                                                                                                                                                                  (P*(12*E*I*wi - 12*E*I*wj + 6*E*I*L*thyi - 6*E*I*L*thyj + A*G*L^3*ks*thyi))/(L*(A*G*ks*L^2 + 12*E*I)) - A*G*ks*(thyi - (12*E*I*wi - 12*E*I*wj + 6*E*I*L*thyi - 6*E*I*L*thyj + A*G*L^3*ks*thyi)/(L*(A*G*ks*L^2 + 12*E*I)))
                                                                                                                                                                                                                                                                                        (E*I*(12*E*I*thyi - 12*E*I*thyj - 6*A*G*L*ks*wi + 6*A*G*L*ks*wj + 4*A*G*L^2*ks*thyi + 2*A*G*L^2*ks*thyj))/(L*(A*G*ks*L^2 + 12*E*I))
                                                                                                                                                                                                                                                                                        (E*I*(12*E*I*thzi - 12*E*I*thzj + 6*A*G*L*ks*vi - 6*A*G*L*ks*vj + 4*A*G*L^2*ks*thzi + 2*A*G*L^2*ks*thzj))/(L*(A*G*ks*L^2 + 12*E*I))
                                                                                                                                                                                                                                                                                                                                                                                                         -(A*E*(ui - uj))/L
 P*((12*E*I*vj - 12*E*I*vi + 6*E*I*L*thzi - 6*E*I*L*thzj + A*G*L^3*ks*thzi)/(L*(A*G*ks*L^2 + 12*E*I)) - (2*(6*E*I*thzi - 6*E*I*thzj + 3*A*G*L*ks*vi - 3*A*G*L*ks*vj + 2*A*G*L^2*ks*thzi + A*G*L^2*ks*thzj))/(A*G*ks*L^2 + 12*E*I) + (3*A*G*L*ks*(2*vi - 2*vj + L*thzi + L*thzj))/(A*G*ks*L^2 + 12*E*I)) - A*G*ks*(thzi - (12*E*I*vj - 12*E*I*vi + 6*E*I*L*thzi - 6*E*I*L*thzj + A*G*L^3*ks*thzi)/(L*(A*G*ks*L^2 + 12*E*I)))
 A*G*ks*(thyi - (12*E*I*wi - 12*E*I*wj + 6*E*I*L*thyi - 6*E*I*L*thyj + A*G*L^3*ks*thyi)/(L*(A*G*ks*L^2 + 12*E*I))) - P*((12*E*I*wi - 12*E*I*wj + 6*E*I*L*thyi - 6*E*I*L*thyj + A*G*L^3*ks*thyi)/(L*(A*G*ks*L^2 + 12*E*I)) - (2*(6*E*I*thyi - 6*E*I*thyj - 3*A*G*L*ks*wi + 3*A*G*L*ks*wj + 2*A*G*L^2*ks*thyi + A*G*L^2*ks*thyj))/(A*G*ks*L^2 + 12*E*I) + (3*A*G*L*ks*(2*wj - 2*wi + L*thyi + L*thyj))/(A*G*ks*L^2 + 12*E*I))
                                                                                                                                                                                                                    -E*I*((2*(6*E*I*thyi - 6*E*I*thyj - 3*A*G*L*ks*wi + 3*A*G*L*ks*wj + 2*A*G*L^2*ks*thyi + A*G*L^2*ks*thyj))/(L*(A*G*ks*L^2 + 12*E*I)) - (6*A*G*ks*(2*wj - 2*wi + L*thyi + L*thyj))/(A*G*ks*L^2 + 12*E*I))
                                                                                                                                                                                                                    -E*I*((2*(6*E*I*thzi - 6*E*I*thzj + 3*A*G*L*ks*vi - 3*A*G*L*ks*vj + 2*A*G*L^2*ks*thzi + A*G*L^2*ks*thzj))/(L*(A*G*ks*L^2 + 12*E*I)) - (6*A*G*ks*(2*vi - 2*vj + L*thzi + L*thzj))/(A*G*ks*L^2 + 12*E*I))];
 

   % 分布载荷矩阵 qx、qy、qz，my、mz are distrbuted load and moment per unit length，respectively
 
FbD =[                                                                    (L*qx)/2
         (L*(A*G*ks*qy*L^2 - 2*A*G*ks*mz*L + 12*E*I*qy))/(2*(A*G*ks*L^2 + 12*E*I))
         (L*(A*G*ks*qz*L^2 + 2*A*G*ks*my*L + 12*E*I*qz))/(2*(A*G*ks*L^2 + 12*E*I))
                                   (6*E*I*L*my)/(A*G*ks*L^2 + 12*E*I) - (L^2*qz)/12
                                   (L^2*qy)/12 + (6*E*I*L*mz)/(A*G*ks*L^2 + 12*E*I)
                                                                            (L*qx)/2
                                 mz + (L*qy)/2 - (12*E*I*mz)/(A*G*ks*L^2 + 12*E*I)
                                 (L*qz)/2 - my + (12*E*I*my)/(A*G*ks*L^2 + 12*E*I)
                                   (L^2*qz)/12 + (6*E*I*L*my)/(A*G*ks*L^2 + 12*E*I)
                                   (6*E*I*L*mz)/(A*G*ks*L^2 + 12*E*I) - (L^2*qy)/12 ];

Fb=FbD+FbC;
%% 考虑圆盘的刚度时
% NLd = [5 6 7 8 23 24 51 52 53 54];
% Ddo = [90 90 90 90 65 90 90 90 90];
%  if any(n == NLd)
%         Do(i) = Ddo;
%     end
%     A=pi*(Do(i)^2-Di(i)^2)/4;
%     I=1/4*pi*((Do(i)/2)^4-(Di(i)/2)^4); 
%     J=1/2*pi*((Do(i)/2)^4-(Di(i)/2)^4);
%     L = Lb(i); 
%     p = Di(i)/Do(i);
%     ks = 6*(1+mju)*(1+p^2)^2/((7+6*mju)*(1+p^2)^2+(20+12*mju)*p^2);
%%
Kb =[  (A*E)/L,                                         0,                                          0,                                                       0,                                                       0, -(A*E)/L,                                          0,                                          0,                                                       0,                                                       0
            0,  (12*A*E*G*I*ks)/(L*(A*G*ks*L^2 + 12*E*I)),                                          0,                                                       0,                    (6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),        0, -(12*A*E*G*I*ks)/(L*(A*G*ks*L^2 + 12*E*I)),                                          0,                                                       0,                    (6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I)
            0,                                          0,  (12*A*E*G*I*ks)/(L*(A*G*ks*L^2 + 12*E*I)),                   -(6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),                                                       0,        0,                                          0, -(12*A*E*G*I*ks)/(L*(A*G*ks*L^2 + 12*E*I)),                   -(6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),                                                       0
            0,                                          0,      -(6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),  (4*E*I*(A*G*ks*L^2 + 3*E*I))/(L*(A*G*ks*L^2 + 12*E*I)),                                                       0,        0,                                          0,       (6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I), -(2*E*I*(6*E*I - A*G*L^2*ks))/(L*(A*G*ks*L^2 + 12*E*I)),                                                       0
            0,       (6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),                                          0,                                                       0,  (4*E*I*(A*G*ks*L^2 + 3*E*I))/(L*(A*G*ks*L^2 + 12*E*I)),        0,      -(6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),                                          0,                                                       0, -(2*E*I*(6*E*I - A*G*L^2*ks))/(L*(A*G*ks*L^2 + 12*E*I))
     -(A*E)/L,                                          0,                                          0,                                                       0,                                                       0,  (A*E)/L,                                          0,                                          0,                                                       0,                                                       0
            0, -(12*A*E*G*I*ks)/(L*(A*G*ks*L^2 + 12*E*I)),                                          0,                                                       0,                   -(6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),        0,  (12*A*E*G*I*ks)/(L*(A*G*ks*L^2 + 12*E*I)),                                          0,                                                       0,                   -(6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I)
            0,                                          0, -(12*A*E*G*I*ks)/(L*(A*G*ks*L^2 + 12*E*I)),                    (6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),                                                       0,        0,                                          0,  (12*A*E*G*I*ks)/(L*(A*G*ks*L^2 + 12*E*I)),                    (6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),                                                       0
            0,                                          0,      -(6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I), -(2*E*I*(6*E*I - A*G*L^2*ks))/(L*(A*G*ks*L^2 + 12*E*I)),                                                       0,        0,                                          0,       (6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),  (4*E*I*(A*G*ks*L^2 + 3*E*I))/(L*(A*G*ks*L^2 + 12*E*I)),                                                       0
            0,       (6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),                                          0,                                                       0, -(2*E*I*(6*E*I - A*G*L^2*ks))/(L*(A*G*ks*L^2 + 12*E*I)),        0,      -(6*A*E*G*I*ks)/(A*G*ks*L^2 + 12*E*I),                                          0,                                                       0,  (4*E*I*(A*G*ks*L^2 + 3*E*I))/(L*(A*G*ks*L^2 + 12*E*I))];
Kbp =[ 0,                                                        0,                                                        0,                                                            0,                                                            0, 0,                                                        0,                                                        0,                                                            0,                                                            0
       0,   P/L + (A^2*G^2*L^3*P*ks^2)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                        0,                                                            0,            (A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2), 0, - P/L - (A^2*G^2*L^3*P*ks^2)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                        0,                                                            0,            (A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2)
       0,                                                        0,   P/L + (A^2*G^2*L^3*P*ks^2)/(5*(A*G*ks*L^2 + 12*E*I)^2),           -(A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                            0, 0,                                                        0, - P/L - (A^2*G^2*L^3*P*ks^2)/(5*(A*G*ks*L^2 + 12*E*I)^2),           -(A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                            0
       0,                                                        0,       -(A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2), (L*P)/12 + (A^2*G^2*L^5*P*ks^2)/(20*(A*G*ks*L^2 + 12*E*I)^2),                                                            0, 0,                                                        0,        (A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2), (A^2*G^2*L^5*P*ks^2)/(20*(A*G*ks*L^2 + 12*E*I)^2) - (L*P)/12,                                                            0
       0,        (A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                        0,                                                            0, (L*P)/12 + (A^2*G^2*L^5*P*ks^2)/(20*(A*G*ks*L^2 + 12*E*I)^2), 0,       -(A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                        0,                                                            0, (A^2*G^2*L^5*P*ks^2)/(20*(A*G*ks*L^2 + 12*E*I)^2) - (L*P)/12
       0,                                                        0,                                                        0,                                                            0,                                                            0, 0,                                                        0,                                                        0,                                                            0,                                                            0
       0, - P/L - (A^2*G^2*L^3*P*ks^2)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                        0,                                                            0,           -(A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2), 0,   P/L + (A^2*G^2*L^3*P*ks^2)/(5*(A*G*ks*L^2 + 12*E*I)^2),                                                        0,                                                            0,           -(A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2)
       0,                                                        0, - P/L - (A^2*G^2*L^3*P*ks^2)/(5*(A*G*ks*L^2 + 12*E*I)^2),            (A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                            0, 0,                                                        0,   P/L + (A^2*G^2*L^3*P*ks^2)/(5*(A*G*ks*L^2 + 12*E*I)^2),            (A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                            0
       0,                                                        0,       -(A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2), (A^2*G^2*L^5*P*ks^2)/(20*(A*G*ks*L^2 + 12*E*I)^2) - (L*P)/12,                                                            0, 0,                                                        0,        (A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2), (L*P)/12 + (A^2*G^2*L^5*P*ks^2)/(20*(A*G*ks*L^2 + 12*E*I)^2),                                                            0
       0,        (A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                        0,                                                            0, (A^2*G^2*L^5*P*ks^2)/(20*(A*G*ks*L^2 + 12*E*I)^2) - (L*P)/12, 0,       -(A^2*G^2*L^4*P*ks^2)/(10*(A*G*ks*L^2 + 12*E*I)^2),                                                        0,                                                            0, (L*P)/12 + (A^2*G^2*L^5*P*ks^2)/(20*(A*G*ks*L^2 + 12*E*I)^2)];
   
   % 整合总体矩阵 载荷尚未考虑
   format long
      MB = BeamAssemble(MB,Mb,i,i+1);
      MC = BeamAssemble(MC,Mc,i,i+1);
      KB = BeamAssemble(KB,Kb,i,i+1);                   % 梁的总刚度矩阵
      KBP = BeamAssemble(KBP,Kbp,i,i+1); 
      GB = BeamAssemble(GB,Gb,i,i+1);                   % 梁的总极转动惯量矩阵
      FB = BeamForceAssemble(FB,Fb,i,i+1);
end
% to abtain MB、MC、KB、KBP、GB、FB
%% 

function y = BeamAssemble(K,k,i,j)
% BeamAssemble       This function assembles the element stiffness
%                    matrix k of the linear bar with nodes i and j 
%                    into the global stiffness matrix K.
%                    This function returns the global stiffness  
%                    matrix K after the element stiffness matrix  
%                    k is assembled.
K(5*i-4,5*i-4) = K(5*i-4,5*i-4) + k(1,1);  K(5*i-4,5*i-3) = K(5*i-4,5*i-3) + k(1,2);
K(5*i-4,5*i-2) = K(5*i-4,5*i-2) + k(1,3);  K(5*i-4,5*i-1) = K(5*i-4,5*i-1) + k(1,4);
K(5*i-4,5*i)   = K(5*i-4,5*i)   + k(1,5);  K(5*i-4,5*j-4) = K(5*i-4,5*j-4) + k(1,6);
K(5*i-4,5*j-3) = K(5*i-4,5*j-3) + k(1,7);  K(5*i-4,5*j-2) = K(5*i-4,5*j-2) + k(1,8);
K(5*i-4,5*j-1) = K(5*i-4,5*j-1) + k(1,9);  K(5*i-4,5*j)   = K(5*i-4,5*j)   + k(1,10);

K(5*i-3,5*i-4) = K(5*i-3,5*i-4) + k(2,1);  K(5*i-3,5*i-3) = K(5*i-3,5*i-3) + k(2,2);
K(5*i-3,5*i-2) = K(5*i-3,5*i-2) + k(2,3);  K(5*i-3,5*i-1) = K(5*i-3,5*i-1) + k(2,4);
K(5*i-3,5*i)   = K(5*i-3,5*i)   + k(2,5);  K(5*i-3,5*j-4) = K(5*i-3,5*j-4) + k(2,6);
K(5*i-3,5*j-3) = K(5*i-3,5*j-3) + k(2,7);  K(5*i-3,5*j-2) = K(5*i-3,5*j-2) + k(2,8);
K(5*i-3,5*j-1) = K(5*i-3,5*j-1) + k(2,9);  K(5*i-3,5*j)   = K(5*i-3,5*j)   + k(2,10);

K(5*i-2,5*i-4) = K(5*i-2,5*i-4) + k(3,1);  K(5*i-2,5*i-3) = K(5*i-2,5*i-3) + k(3,2);
K(5*i-2,5*i-2) = K(5*i-2,5*i-2) + k(3,3);  K(5*i-2,5*i-1) = K(5*i-2,5*i-1) + k(3,4);
K(5*i-2,5*i)   = K(5*i-2,5*i)   + k(3,5);  K(5*i-2,5*j-4) = K(5*i-2,5*j-4) + k(3,6);
K(5*i-2,5*j-3) = K(5*i-2,5*j-3) + k(3,7);  K(5*i-2,5*j-2) = K(5*i-2,5*j-2) + k(3,8);
K(5*i-2,5*j-1) = K(5*i-2,5*j-1) + k(3,9);  K(5*i-2,5*j)   = K(5*i-2,5*j)   + k(3,10);

K(5*i-1,5*i-4) = K(5*i-1,5*i-4) + k(4,1);  K(5*i-1,5*i-3) = K(5*i-1,5*i-3) + k(4,2);
K(5*i-1,5*i-2) = K(5*i-1,5*i-2) + k(4,3);  K(5*i-1,5*i-1) = K(5*i-1,5*i-1) + k(4,4);
K(5*i-1,5*i)   = K(5*i-1,5*i)   + k(4,5);  K(5*i-1,5*j-4) = K(5*i-1,5*j-4) + k(4,6);
K(5*i-1,5*j-3) = K(5*i-1,5*j-3) + k(4,7);  K(5*i-1,5*j-2) = K(5*i-1,5*j-2) + k(4,8);
K(5*i-1,5*j-1) = K(5*i-1,5*j-1) + k(4,9);  K(5*i-1,5*j)   = K(5*i-1,5*j)   + k(4,10);

K(5*i,5*i-4) = K(5*i,5*i-4) + k(5,1);  K(5*i,5*i-3) = K(5*i,5*i-3) + k(5,2);
K(5*i,5*i-2) = K(5*i,5*i-2) + k(5,3);  K(5*i,5*i-1) = K(5*i,5*i-1) + k(5,4);
K(5*i,5*i)   = K(5*i,5*i)   + k(5,5);  K(5*i,5*j-4) = K(5*i,5*j-4) + k(5,6);
K(5*i,5*j-3) = K(5*i,5*j-3) + k(5,7);  K(5*i,5*j-2) = K(5*i,5*j-2) + k(5,8);
K(5*i,5*j-1) = K(5*i,5*j-1) + k(5,9);  K(5*i,5*j)   = K(5*i,5*j)   + k(5,10);

K(5*j-4,5*i-4) = K(5*j-4,5*i-4) + k(6,1);  K(5*j-4,5*i-3) = K(5*j-4,5*i-3) + k(6,2);
K(5*j-4,5*i-2) = K(5*j-4,5*i-2) + k(6,3);  K(5*j-4,5*i-1) = K(5*j-4,5*i-1) + k(6,4);
K(5*j-4,5*i)   = K(5*j-4,5*i)   + k(6,5);  K(5*j-4,5*j-4) = K(5*j-4,5*j-4) + k(6,6);
K(5*j-4,5*j-3) = K(5*j-4,5*j-3) + k(6,7);  K(5*j-4,5*j-2) = K(5*j-4,5*j-2) + k(6,8);
K(5*j-4,5*j-1) = K(5*j-4,5*j-1) + k(6,9);  K(5*j-4,5*j)   = K(5*j-4,5*j)   + k(6,10);

K(5*j-3,5*i-4) = K(5*j-3,5*i-4) + k(7,1);  K(5*j-3,5*i-3) = K(5*j-3,5*i-3) + k(7,2);
K(5*j-3,5*i-2) = K(5*j-3,5*i-2) + k(7,3);  K(5*j-3,5*i-1) = K(5*j-3,5*i-1) + k(7,4);
K(5*j-3,5*i)   = K(5*j-3,5*i)   + k(7,5);  K(5*j-3,5*j-4) = K(5*j-3,5*j-4) + k(7,6);
K(5*j-3,5*j-3) = K(5*j-3,5*j-3) + k(7,7);  K(5*j-3,5*j-2) = K(5*j-3,5*j-2) + k(7,8);
K(5*j-3,5*j-1) = K(5*j-3,5*j-1) + k(7,9);  K(5*j-3,5*j)   = K(5*j-3,5*j)   + k(7,10);

K(5*j-2,5*i-4) = K(5*j-2,5*i-4) + k(8,1);  K(5*j-2,5*i-3) = K(5*j-2,5*i-3) + k(8,2);
K(5*j-2,5*i-2) = K(5*j-2,5*i-2) + k(8,3);  K(5*j-2,5*i-1) = K(5*j-2,5*i-1) + k(8,4);
K(5*j-2,5*i)   = K(5*j-2,5*i)   + k(8,5);  K(5*j-2,5*j-4) = K(5*j-2,5*j-4) + k(8,6);
K(5*j-2,5*j-3) = K(5*j-2,5*j-3) + k(8,7);  K(5*j-2,5*j-2) = K(5*j-2,5*j-2) + k(8,8);
K(5*j-2,5*j-1) = K(5*j-2,5*j-1) + k(8,9);  K(5*j-2,5*j)   = K(5*j-2,5*j)   + k(8,10);

K(5*j-1,5*i-4) = K(5*j-1,5*i-4) + k(9,1);  K(5*j-1,5*i-3) = K(5*j-1,5*i-3) + k(9,2);
K(5*j-1,5*i-2) = K(5*j-1,5*i-2) + k(9,3);  K(5*j-1,5*i-1) = K(5*j-1,5*i-1) + k(9,4);
K(5*j-1,5*i)   = K(5*j-1,5*i)   + k(9,5);  K(5*j-1,5*j-4) = K(5*j-1,5*j-4) + k(9,6);
K(5*j-1,5*j-3) = K(5*j-1,5*j-3) + k(9,7);  K(5*j-1,5*j-2) = K(5*j-1,5*j-2) + k(9,8);
K(5*j-1,5*j-1) = K(5*j-1,5*j-1) + k(9,9);  K(5*j-1,5*j)   = K(5*j-1,5*j)   + k(9,10);

K(5*j,5*i-4) = K(5*j,5*i-4) + k(10,1);  K(5*j,5*i-3) = K(5*j,5*i-3) + k(10,2);
K(5*j,5*i-2) = K(5*j,5*i-2) + k(10,3);  K(5*j,5*i-1) = K(5*j,5*i-1) + k(10,4);
K(5*j,5*i)   = K(5*j,5*i)   + k(10,5);  K(5*j,5*j-4) = K(5*j,5*j-4) + k(10,6);
K(5*j,5*j-3) = K(5*j,5*j-3) + k(10,7);  K(5*j,5*j-2) = K(5*j,5*j-2) + k(10,8);
K(5*j,5*j-1) = K(5*j,5*j-1) + k(10,9);  K(5*j,5*j)   = K(5*j,5*j)   + k(10,10);

y = K;

function y=BeamForceAssemble(FB,Fb,i,j)

FB(5*i-4,1) = FB(5*i-4,1) + Fb(1,1);
FB(5*i-3,1) = FB(5*i-3,1) + Fb(2,1);
FB(5*i-2,1) = FB(5*i-2,1) + Fb(3,1);
FB(5*i-1,1) = FB(5*i-1,1) + Fb(4,1);
FB(5*i,1)   = FB(5*i,1)   + Fb(5,1);

FB(5*j-4,1) = FB(5*j-4,1) + Fb(6,1);
FB(5*j-3,1) = FB(5*j-3,1) + Fb(7,1);
FB(5*j-2,1) = FB(5*j-2,1) + Fb(8,1);
FB(5*j-1,1) = FB(5*j-1,1) + Fb(9,1);
FB(5*j,1)   = FB(5*j,1)   + Fb(10,1);

y=FB;
  